POST http://localhost:8080/sendMail HTTP/1.1
content-type: application/json

{
    "text": "Opa"
}

###

POST http://www.gardelsouza.net/sendMail HTTP/1.1
content-type: application/json

{
    "text": "Olar"
}