GET https://localhost:5001/WeatherForecast/ HTTP/1.1
###
GET https://localhost:5001/WeatherForecast/3 HTTP/1.1
###
POST https://localhost:5001/WeatherForecast/ HTTP/1.1
content-type: application/json

{
    "Date": "2020-03-10T12:50:00",
    "TemperatureC": 30,
    "Summary": "Teste 2"
}
###
PUT https://localhost:5001/WeatherForecast/ HTTP/1.1
content-type: application/json

{
    "Id": 2,
    "Date": "2020-03-10T12:50:00",
    "TemperatureC": 30,
    "Summary": "Teste 22"
}
###
DELETE https://localhost:5001/WeatherForecast/1 HTTP/1.1
content-type: application/json
